#!/usr/bin/env python
Import('env')

env_module = env.Clone()

# Thirdparty sources
thirdparty_dirs = [
    "thirdparty/exoquant/",
    "thirdparty/hq3x/",
]
thirdparty_sources = []
thirdparty_sources += Glob("thirdparty/exoquant/*.c")
thirdparty_sources += Glob("thirdparty/hqx/*.cc")

env_thirdparty = env_module.Clone()
env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)
env_thirdparty.disable_warnings()
env_thirdparty.Append(CPPPATH='thirdparty/')

env_module.Append(CPPPATH='.')
env_module.Append(CPPPATH='thirdparty/')
env_module.Append(CPPPATH='classes/')

# Module sources
env_module.add_source_files(env.modules_sources, '*.cpp')
env_module.add_source_files(env.modules_sources, 'bind/*.cpp')
env_module.add_source_files(env.modules_sources, 'classes/*.cpp')
env_module.add_source_files(env.modules_sources, 'drivers/png/*.cpp')

Export('env_module')
